openapi: 3.0.0
info:
  title: Api del panel administrativo
  version: '1.0'
  description: |
    Servicio que  permite al comercio listar y ver detalle de las solicitudes de validación de identidad. 
  contact:
    name: Daniela Rodríguez Higuita
    email: daniela.rodriguez@evertecinc.com
servers:
  - url: 'http://onboarding.localhost/api'
    description: onboarding.localhost(Desarrollo)
paths:
  /onboarding-requets:
    get:
      summary: Enlistar solicitudes de validación
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/OnBoardingRequest'
                  links:
                    type: object
                    description: Navegación de la paginación
                    properties:
                      self:
                        type: string
                      first:
                        type: string
                        description: Ruta de navegación que indica la primera página
                      last:
                        type: string
                        description: Ruta de navegación que indica la última página
                      next:
                        type: string
                        description: Ruta de navegación que indica la última página
                  meta:
                    type: object
                    description: 'Información de las consultas '
                    properties:
                      current_page:
                        description: Indica el número de la página actual
                        type: number
                      from:
                        description: 'Indica el número de la solicitud inicial en la busqueda '
                        type: number
                      last_page:
                        type: number
                        description: 'Indica el número de la última página '
                      path:
                        type: string
                        description: Ruta donde se realiza la consulta
                      per_page:
                        description: Cantidad de solicitudes por página
                        type: number
                      to:
                        description: 'Indica el número de la solicitud final en la busqueda '
                        type: number
                      total:
                        type: number
                        description: Total de solicitudes de validación de identidad
              examples:
                Exitosa consulta de solicitudes:
                  value:
                    data:
                      - id: 3006747
                        document_type_id: 1
                        document: ipsum amet ea aute
                        document_issue_date: '2013-02-28'
                        names: minim laboris
                        surnames: adipisicing Duis mollit enim est
                        cellphone: c
                        cellphone_country: deserunt Lorem qui
                        email: dolore
                        device_channel: UNDEFINED
                        device_fingerprint: []
                        status: COMPLETED
                        status_message: non aliqua
                        reply_sent: false
                        response: []
                        created_at: '2015-06-03'
                      - id: 67678087
                        document_type_id: 2
                        document: voluptate officia eu
                        document_issue_date: '2020-02-28'
                        names: Excepteur Lorem
                        surnames: eiusmod et non sint do
                        cellphone: tempor sunt
                        cellphone_country: sit in
                        email: officia in
                        device_channel: UNDEFINED
                        device_fingerprint: []
                        status: COMPLETED
                        status_message: minim sint
                        reply_sent: true
                        response: []
                        created_at: '1989-05-13'
                      - id: 47071858
                        document_type_id: 1
                        document: Lorem laborum
                        document_issue_date: '1982-11-30'
                        names: et enim laboris aliqua
                        surnames: adipisicing
                        cellphone: in
                        cellphone_country: dese
                        email: incididunt velit quis
                        device_channel: UNDEFINED
                        device_fingerprint: []
                        status: PROCESSING
                        status_message: in sint qui aliquip dolor
                        reply_sent: false
                        response: []
                        created_at: '2017-07-15'
                    links:
                      self: link-value
                      first: 'http://onboarding.localhost/api/onboarding-requests?page=1'
                      last: 'http://onboarding.localhost/api/onboarding-requests?page=1'
                      next: null
                    meta:
                      current_page: 1
                      from: 1
                      last_page: 1
                      path: 'http://onboarding.localhost/api/onboarding-requests'
                      per_page: 15
                      to: 5
                      total: 5
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Token erróneo o no envió de la cabecera authorization:
                  value:
                    data: null
                    errors: null
                    status:
                      status: UNAUTHENTICATED
                      reason: ''
                      message: Estas credenciales no coinciden con nuestros registros.
                      date: '2020-07-10T04:18:44+00:00'
            application/xml:
              schema:
                type: object
                properties: {}
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Inclumiento en la validación de los datos:
                  value:
                    data: null
                    errors:
                      merchant_external_id:
                        - El campo merchant external id es obligatorio.
                    status:
                      status: FAILED
                      reason: ''
                      message: Los datos proporcionados no son válidos.
                      date: '2020-07-08T19:00:43+00:00'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Error durante el procesamiento de la petición:
                  value:
                    data: null
                    errors: null
                    status:
                      status: FAILED
                      reason: ''
                      message: ''
                      date: '2020-05-12T14:27:06+00:00'
      operationId: get-onboarding-requets
      description: Enlistar y filtrar las solicitudes de validación de identidad de acuerdo a la identificación del comercio.
      parameters:
        - schema:
            type: integer
          in: query
          name: merchant_external_id
          description: Identificación única e individual otorgada por Evertec al comercio.
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          description: |
            application/json
          required: true
        - schema:
            type: integer
            minimum: 1
          in: query
          name: id
          description: Identificador único de la petición de validación de identidad
        - schema:
            type: string
            minLength: 4
            maxLength: 30
          in: query
          name: document
          description: |
            Numéro del documento de identidad
        - schema:
            type: string
            minLength: 2
            maxLength: 60
            pattern: '/^[a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã][a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã\''\.\&\-\d ]{2,60}$/i'
          in: query
          name: names
          description: Nombres de la persona a consultar
        - schema:
            type: string
            minLength: 2
            maxLength: 0
            pattern: '/^[a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã][a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã\''\.\&\-\d ]{2,60}$/i'
          in: query
          name: surnames
          description: Apellidos de la persona a consultar
        - schema:
            type: string
            enum:
              - CREATED
              - PROCESSING
              - COMPLETED
              - PARTIAL_COMPLETED
              - FAILED
            example: FAILED
          in: query
          name: status
          description: Estado final de la petición
        - schema:
            type: string
            format: date
            example: '2020-06-25'
          in: query
          name: created_at
          description: Fecha de creación de la petición(Y-m-d)
        - schema:
            type: number
          in: query
          name: per_page
          description: Cantidad de peticiones deseada por página
        - schema:
            type: string
          in: header
          name: Content-Type
          description: |
            application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer token_provisto_por_placetopay
          required: true
  '/onboarding-requests/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: Identificador de la solicitud de validación
    get:
      summary: Ver detalle de una solicitud de validación
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/OnBoardingRequest'
                  services:
                    type: array
                    description: Dellate de los servicios consumidos en la solicitud de validación
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          minimum: 1
                          description: Identificación del servicio
                        service:
                          type: string
                          enum:
                            - SARLAFT
                            - PERSONAL_INFORMATION
                          description: Nombre del servicio
                        status:
                          type: string
                          enum:
                            - CREATED
                            - PROCESSING
                            - COMPLETED
                            - FAILED
                        inquiry:
                          type: string
              examples:
                Exitosa consulta de los detalles de una validación:
                  value:
                    data:
                      id: 1
                      document_type_id: 1
                      document: '1061718031'
                      document_issue_date: '2007-04-25'
                      names: Veronica
                      surnames: Restrepo
                      cellphone: '3152364205'
                      cellphone_country: CO
                      email: test@placetopay.com
                      device_channel: BROWSER
                      device_fingerprint:
                        - abc: 123
                      status: COMPLETED
                      status_message: ''
                      reply_sent: false
                      response: []
                      created_at: '2020-07-09'
                      services:
                        - id: 1
                          service: SARLAFT
                          status: COMPLETED
                          inquiry:
                            id: 1
                            is_risk: true
                            peps: []
                            lists:
                              - Link: null
                                Alias: 'THE CHESS PLAYER (A.K.A), LUCAS (A.K.A)'
                                Hecho: null
                                Delito: ''
                                Riesgo: ''
                                Actividad: PN EC
                                Conclusion: Positivo Lista Restrictiva Homonimo
                                NombreBase: null
                                TextoLargo: null
                                NombreLista: OFAC
                                OrigenLista: INTERNACIONAL
                                Coincidencia: ID
                                ListasNombre: RODRIGUEZ OREJUELA GILBERTO JOSE
                                Nacionalidad: Colombia
                                PedidoNombre: null
                                PedidoTipoId: '1'
                                RelacionadoCon: ''
                                EstadoMatricula: Cancelada
                                UltFechaBoletin: '20190822'
                                NroNombreValidos: '-'
                                NacionalidadListas: EEUU
                                EstadoPersonaNatural: Vigente
                                PorcentajeCoincidencia: 100%
                                ListasNroIdentificacion: '6067015'
                                NroIdentificacionValido: Válido
                                PedidoNroIdentificacion: '6067015'
                                EstadoNitPersonaJuridica: No Reinscripto
                                ListasTipoIdentificacion: CC
                              - Link: null
                                Alias: ''
                                Hecho: null
                                Delito: ''
                                Riesgo: ''
                                Actividad: PN EC
                                Conclusion: Positivo Lista Restrictiva ID
                                NombreBase: null
                                TextoLargo: null
                                NombreLista: PROCURADURIA
                                OrigenLista: COLOMBIA
                                Coincidencia: ID
                                ListasNombre: GILBERTO JOSE RODRIGUEZ OREJUELA
                                Nacionalidad: Colombia
                                PedidoNombre: null
                                PedidoTipoId: '1'
                                RelacionadoCon: 'TRAFICO, FABRICACION O PORTE DE ESTUPEFACIENTES LEY 599 DE 2000 (LEY 599 DE 2000) -- '
                                EstadoMatricula: Cancelada
                                UltFechaBoletin: '20071221'
                                NroNombreValidos: '-'
                                NacionalidadListas: COLOMBIA
                                EstadoPersonaNatural: Vigente
                                PorcentajeCoincidencia: 100%
                                ListasNroIdentificacion: '6067015'
                                NroIdentificacionValido: Válido
                                PedidoNroIdentificacion: '6067015'
                                EstadoNitPersonaJuridica: No Reinscripto
                                ListasTipoIdentificacion: CC
                            news: []
                        - id: 2
                          service: PERSONAL_INFORMATION
                          status: COMPLETED
                          inquiry:
                            id: 1
                            status: WITH_INFORMATION
                            name_match_percentage: 33.96
                            email_match: true
                            cellphone_match: true
                            information:
                              user: Cifin Calidad Identificacion Pruebas
                              cards:
                                - brand:
                                    code: '4'
                                    description: MasterCard
                                  class:
                                    code: '9'
                                    description: Standard
                                  entity:
                                    code: 1
                                    name: BANCO DE BOGOTÁ
                                  number: '097106'
                                  status:
                                    code: '21'
                                    description: Cancelada voluntariamente
                              emails:
                                - email: test@placetopay.com
                                  numReports: 1
                                  lastReportDate: '2010-02-06'
                                - email: test1@placetopay.com
                                  numReports: 10
                                  lastReportDate: '2019-02-06'
                              person:
                                name: Cifin Calidad
                                surname: Identificacion Pruebas
                                ageRange: 25-30
                                fullName: Identificacion Pruebas Cifin Calidad
                              phones:
                                - city: BOGOTA ( BOGOTA DISTRITO CA )
                                  type: RES
                                  number: '7801825'
                                  numReports: 1
                                  lastReportDate: '1970-01-01'
                              mobiles:
                                - type: CEL
                                  number: '3152364205'
                                  numReports: 2
                                  lastReportDate: '1970-01-01'
                                - type: CEL
                                  number: '3138777073'
                                  numReports: 2
                                  lastReportDate: '1970-01-01'
                              document:
                                type:
                                  code: 1
                                  alias: CC
                                  description: Cedula de ciudadanía
                                number: '1012388476'
                                status:
                                  code: 1
                                  description: Vigente
                                issueDate: '1970-01-01'
                                issuePlace: BOGOTA D.C.
                              addresses:
                                - city: BOGOTA ( BOGOTA DISTRITO CA )
                                  address: 'KR 7 # 17 - 01 PI 3'
                                  numReports: 2
                                  lastReportDate: '2014-04-30'
                                - city: BOGOTA ( BOGOTA DISTRITO CA )
                                  address: 'DG 39 B SUR # 35 - 24'
                                  numReports: 2
                                  lastReportDate: '2012-03-13'
                                - city: BOGOTA ( BOGOTA DISTRITO CA )
                                  address: 'DG 39 B SUR # 0 B - 39'
                                  numReports: 1
                                  lastReportDate: '2011-08-22'
                                - city: BOGOTA ( BOGOTA DISTRITO CA )
                                  address: 'KR 72 J # 43 - 40 SUR CS 41 A'
                                  numReports: 2
                                  lastReportDate: '2009-03-12'
                              requestDate: '2020-09-07'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Token erróneo o no envió de la cabecera authorization:
                  value:
                    data: null
                    errors: null
                    status:
                      status: UNAUTHENTICATED
                      reason: ''
                      message: Estas credenciales no coinciden con nuestros registros.
                      date: '2020-07-10T04:51:25+00:00'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Ver detalle de una request inexistente:
                  value:
                    data: null
                    errors: null
                    status:
                      status: FAILED
                      reason: ''
                      message: El modelo proporcionado no fue encontrado
                      date: '2020-07-10T15:32:35+00:00'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Inclumiento en la validación de los datos:
                  value:
                    data: null
                    errors:
                      identification:
                        - identificación debe ser un número entero.
                    status:
                      status: FAILED
                      reason: ''
                      message: Los datos proporcionados no son válidos.
                      date: '2020-08-04T20:42:44+00:00'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnBoardingResponse'
              examples:
                Error durante el procesamiento de la petición:
                  value:
                    data: null
                    errors: null
                    status:
                      status: FAILED
                      reason: ''
                      message: ''
                      date: '2020-05-12T14:27:06+00:00'
      operationId: get-onboarding-requests-onBoardingRequest
      description: Ver detalle de una solicitud de validación
      parameters:
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          required: true
          description: |
            application/json
        - schema:
            type: string
          in: header
          name: Content-type
          description: application/json
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
          description: Token provisto por Evertec-placetopay
components:
  schemas:
    OnBoardingRequest:
      title: OnBoardingRequest
      type: object
      description: Representa los datos asociados a una solicitud de validación de identidad.
      properties:
        id:
          type: integer
          description: Identificación de la solicitud
          minimum: 1
        document_type:
          type: string
          description: |-
            Identificación del tipo de documento 
            CC = Cédula de Ciudadanía 
            CE = Cédula de Extranjería
          enum:
            - CC
            - CE
        document:
          type: string
          description: |-
            Iniciales correspondiente con el tipo de
            documento
          pattern: 'CC => ''/^[1-9][0-9]{3,9}$/''  CE =>''/^([a-zA-Z]{1,5})?[1-9][0- 9]{3,7}$/'''
          minLength: 1
          maxLength: 30
        document_issue_date:
          type: string
          description: Fecha de expedición del documento(Y-m-d)
          format: date
        name:
          type: string
          description: Nombres completos
          pattern: '/^[a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã][a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã\''\.\&\-\d ]{2,60}$/i'
          minLength: 1
          maxLength: 60
        surname:
          type: string
          description: Apellidos completos
          pattern: '/^[a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã][a-zñáéíóúäëïöüàèìòùÑÁÉÍÓÚÄËÏÖÜÀÈÌÒÙÇçÃã\''\.\&\-\d ]{2,60}$/i'
        email:
          type: string
          pattern: '''/^([a-zA-Z0-9_\.\-])+[^\.\-\ ]\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})$/'''
          maxLength: 150
          minLength: 7
          format: email
          description: Número de línea telefónica móvil
        mobile:
          type: string
          pattern: '''/^\+?(57)?(\d{10})$/'''
          minLength: 1
          maxLength: 30
          description: Número de línea telefónica móvil
        mobile_country:
          type: string
          enum:
            - CO
          description: ISO 3166/2 código del país de la lìnea de celular
        device_channel:
          type: string
          enum:
            - BROWSER
            - APPLICATION
          description: |-
            Identificador de la fuente de la petición de
            autenticación de identidad (navegador web o app)
        device_fingerprint:
          type: array
          description: Huella digital del dispositivo desde el que se lleva a cabo el proceso de incorporación
          items: {}
        status:
          type: string
          enum:
            - FAILED
            - COMPLETED
            - CREATED
            - PROCESSING
            - PARTIAL_COMPLETED
            - REJECTED_BY_EXCLUDED_LIST
          description: Estado de la solicitud
        created_at:
          type: string
          format: date
          description: Fecha de creación
      required:
        - id
        - document_type
        - document
        - document_issue_date
        - name
        - surname
        - email
        - mobile
        - mobile_country
        - status
    OnBoardingResponse:
      title: OnBoardingResponse
      type: object
      properties:
        data:
          type: object
        errors:
          type: string
        status:
          type: object
          properties:
            status:
              type: string
            reason:
              type: string
            message:
              type: string
            date:
              type: string
              format: date
      description: Estructura general de la respuesta que genera la petición de un servicio  ofrecido
  securitySchemes:
    Bearer *****************:
      name: Authorization
      type: apiKey
      in: header
      description: |-
        Para autenticar una solicitud, se debe proporcionar el encabezado Authorization junto con el
        valor Bearer seguido del token asignado al comercio.
security:
  - API Key - 1: []
